// Auto-generated by: npm run db:types
// Run this command after any schema change to regenerate.
// Do NOT edit manually — your changes will be overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          full_name: string | null
          avatar_url: string | null
          bio: string | null
          website_url: string | null
          is_public: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          website_url?: string | null
          is_public?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      personas: {
        Row: {
          id: string
          profile_id: string
          slug: string
          title: string
          purpose: 'job_seeker' | 'creator' | 'freelancer' | 'consultant'
          description: string | null
          is_active: boolean
          chat_enabled: boolean
          chat_greeting: string | null
          metadata: Json
          structured_profile: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          slug: string
          title: string
          purpose: 'job_seeker' | 'creator' | 'freelancer' | 'consultant'
          description?: string | null
          is_active?: boolean
          chat_enabled?: boolean
          chat_greeting?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['personas']['Insert']>
      }
      documents: {
        Row: {
          id: string
          persona_id: string
          profile_id: string
          name: string
          original_name: string
          doc_type: 'cv' | 'portfolio' | 'bio' | 'link' | 'certificate' | 'other'
          file_url: string | null
          content: string | null
          status: 'pending' | 'processing' | 'ready' | 'error'
          pipeline_stage: string
          error_message: string | null
          chunk_count: number
          word_count: number | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          persona_id: string
          profile_id: string
          name: string
          original_name: string
          doc_type?: 'cv' | 'portfolio' | 'bio' | 'link' | 'certificate' | 'other'
          file_url?: string | null
          content?: string | null
          status?: 'pending' | 'processing' | 'ready' | 'error'
          pipeline_stage?: string
          error_message?: string | null
          chunk_count?: number
          word_count?: number | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['documents']['Insert']>
      }
      document_chunks: {
        Row: {
          id: string
          document_id: string
          persona_id: string
          content: string
          embedding: number[] | null
          chunk_index: number
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          document_id: string
          persona_id: string
          content: string
          embedding?: number[] | null
          chunk_index?: number
          metadata?: Json
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['document_chunks']['Insert']>
      }
      chat_sessions: {
        Row: {
          id: string
          persona_id: string
          visitor_id: string | null
          visitor_email: string | null
          visitor_name: string | null
          visitor_purpose: string | null
          session_metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          persona_id: string
          visitor_id?: string | null
          visitor_email?: string | null
          visitor_name?: string | null
          visitor_purpose?: string | null
          session_metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['chat_sessions']['Insert']>
      }
      chat_messages: {
        Row: {
          id: string
          session_id: string
          role: 'user' | 'assistant' | 'system'
          content: string
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          role: 'user' | 'assistant' | 'system'
          content: string
          metadata?: Json
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['chat_messages']['Insert']>
      }
      contact_requests: {
        Row: {
          id: string
          session_id: string
          persona_id: string
          requester_email: string
          requester_name: string
          requester_org: string | null
          subject: string
          message: string
          status: 'pending' | 'seen' | 'accepted' | 'declined'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_id: string
          persona_id: string
          requester_email: string
          requester_name: string
          requester_org?: string | null
          subject: string
          message: string
          status?: 'pending' | 'seen' | 'accepted' | 'declined'
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['contact_requests']['Insert']>
      }
      notifications: {
        Row: {
          id: string
          profile_id: string
          type: string
          subject: string
          payload: Json
          sent_at: string | null
          error: string | null
          created_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          type: string
          subject: string
          payload?: Json
          sent_at?: string | null
          error?: string | null
          created_at?: string
        }
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>
      }
    }
    Functions: {
      search_chunks: {
        Args: {
          query_embedding: number[]
          target_persona: string
          match_threshold?: number
          match_count?: number
        }
        Returns: {
          id: string
          content: string
          metadata: Json
          similarity: number
        }[]
      }
    }
    Enums: Record<string, never>
  }
}
